export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
export const VIEW_LISTS = 'VIEW_LISTS'
export const ADD_LIST = 'ADD_LIST'
export const EDIT_LIST = 'EDIT_LIST'
export const ADD_ITEM = 'ADD_ITEM'
export const MENU = 'MENU'
export const LOGIN = 'LOGIN'